### ISSUE TITLE
Running "Rescue" on VMware provided host fails

### ISSUE THREAD

**Issue by xTrekStorex** [dm-drogeriemarkt/foreman_rescue#6]
Running "Rescue" on VMware provided host fails with `uninitialized constant Fog::Compute::Ovirt` - no ovirt compute resource present, plugin not installed.
Foreman 1.16.1, Debian 9.4, VMware vSphere 6.5 (latest update), Puppet5

Stacktrace:
```NameError
uninitialized constant Fog::Compute::Ovirt
/usr/share/foreman/app/services/power_manager/virt.rb:35:in `default_action'
/usr/share/foreman/app/services/power_manager/base.rb:25:in `block (2 levels) in '
/usr/share/foreman/app/models/concerns/hostext/power_interface.rb:22:in `supports_power_and_running?'
/usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/foreman_rescue-1a3c2a247f06/app/views/foreman_rescue/hosts/rescue.html.erb:60:in `block in _a6295b48f200657382c96f97b948b7fa'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/helpers/capture_helper.rb:38:in `capture'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/helpers/form_helper.rb:444:in `form_for'
/usr/share/foreman/app/helpers/form_helper.rb:290:in `form_for'
/usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/foreman_rescue-1a3c2a247f06/app/views/foreman_rescue/hosts/rescue.html.erb:50:in `_a6295b48f200657382c96f97b948b7fa'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/template.rb:145:in `block in render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:166:in `instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/template.rb:333:in `instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/template.rb:143:in `render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/deface-1.2.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/renderer.rb:46:in `render_template'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/renderer/renderer.rb:27:in `render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/rendering.rb:100:in `_render_template'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/rendering.rb:25:in `render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rendering.rb:16:in `render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-4.2.9/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:43:in `render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:198:in `process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/share/foreman/app/controllers/concerns/application_shared.rb:15:in `set_timezone'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:497:in `block in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:497:in `block in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:497:in `block in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/share/foreman/vendor/ruby/2.3.0/gems/audited-4.5.0/lib/audited/sweeper.rb:14:in `around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:455:in `public_send'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:455:in `block in make_lambda'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:497:in `block in around'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164:in `instrument'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-4.2.9/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:137:in `process'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/rendering.rb:30:in `process'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:196:in `dispatch'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:237:in `block in action'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:817:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/apipie-rails-0.5.7/lib/apipie/static_dispatcher.rb:65:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/apipie-rails-0.5.7/lib/apipie/extractor/recorder.rb:136:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/apipie-rails-0.5.7/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/etag.rb:24:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/conditionalget.rb:25:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/head.rb:13:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/share/foreman/lib/middleware/catch_json_parse_errors.rb:8:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/share/foreman/lib/middleware/session_safe_logging.rb:17:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/session/abstract/id.rb:225:in `context'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/session/abstract/id.rb:220:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-4.2.9/lib/active_record/query_cache.rb:36:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:38:in `call_app'
/usr/share/foreman/vendor/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:22:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/usr/share/foreman/lib/middleware/tagged_logging.rb:18:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/methodoverride.rb:22:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/runtime.rb:18:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/static.rb:120:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/sendfile.rb:113:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/secure_headers-3.7.3/lib/secure_headers/middleware.rb:12:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:518:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/railties-4.2.9/lib/rails/application.rb:165:in `call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `public_send'
/usr/share/foreman/vendor/ruby/2.3.0/gems/railties-4.2.9/lib/rails/railtie.rb:194:in `method_missing'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/urlmap.rb:66:in `block in call'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/urlmap.rb:50:in `each'
/usr/share/foreman/vendor/ruby/2.3.0/gems/rack-1.6.9/lib/rack/urlmap.rb:50:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
/usr/share/foreman/vendor/ruby/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'

**Comment by timogoebel** [comment]
@xTrekStorex: Please see this Redmine issue for details, a workaround and a fix: https://projects.theforeman.org/issues/23212
